package or.mejdys.entities;

// Generated Jun 4, 2014 1:08:09 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Roles generated by hbm2java
 */
public class Roles implements java.io.Serializable {

	private int roleId;
	private String roleName;
	private Set userses = new HashSet(0);

	public Roles() {
	}

	public Roles(int roleId, String roleName) {
		this.roleId = roleId;
		this.roleName = roleName;
	}

	public Roles(int roleId, String roleName, Set userses) {
		this.roleId = roleId;
		this.roleName = roleName;
		this.userses = userses;
	}

	public int getRoleId() {
		return this.roleId;
	}

	public void setRoleId(int roleId) {
		this.roleId = roleId;
	}

	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	public Set getUserses() {
		return this.userses;
	}

	public void setUserses(Set userses) {
		this.userses = userses;
	}

}
